# Use an official Node.js image as the base
FROM node:18

# Set the working directory inside the container
WORKDIR /dockerfile

# Copy only the package.json and package-lock.json first to install dependencies
COPY package*.json ./

# Install node dependencies
RUN npm install

# Copy the rest of your application code
COPY . .

# Expose the backend port
EXPOSE 5000

# Command to run your app
CMD ["node", "index.js"]
